### ISSUE TITLE
Crash with AnypoinStudio when opening the preview

### ISSUE THREAD

**Issue by ak1394** [42Crunch/eclipse-openapi#8]
When attempting preview OpenAPI which is either not part of a project, or prior to the moment when OpenAPI perspective have been shown, IDE crashes. One of the stacktraces: 

!ENTRY org.eclipse.e4.ui.workbench 4 0 2022-03-28 15:42:20.352
!MESSAGE Command 'com.xliic.openapi.actions.SecurityAuditAction' failed
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'com.xliic.openapi.actions.SecurityAuditAction': java.lang.NullPointerException
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
        at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

**Comment by anthony-42crunch** [comment]
Anypoint Studio Version: 7.21.0
OpenAPI (Swagger) Editor Version 1.0.78

Cannot reproduce a crash. 
Attempting to run preview when the target file is not a part of the project correctly displays an error modal, and does not crash the IDE. 

<img width="1147" alt="Image" src="https://github.com/user-attachments/assets/e2ccfc14-bbbc-4126-9d09-35a738d244f4" />
